### PR TITLE
Pull request from pack 57 fork

### PR DESCRIPTION
**Pull request by sly4**
Model tweaks,
Added link from admin/race to observer view,
Added link from admin/current to control view,
Added racer images to admin/racer list view,
CSS update for racer image scaling,
Image cropper update.

### CODE REVIEW

**Comment by sly4** [comment]
Hi Robb,

I might have handled this incorrectly.  I have extensive experience with subversion, but not so much with git.  I'm not sure what the best way is to cherry pick changes from branch to branch yet.  It might make sense to scrap this pull request if you can't selectively bring over specific changes.  I can change how I'm organized on my end to keep my fork's master branch inline with yours.  Then merges can be more sensible.

**Comment by joneser005** [comment]
I am pretty green with Git.  So far as I can tell, accepting a pull request is an all-or-nothing affair.  It might be best to keep them small & focused.  I will try to do same, assuming pull requests can go either direction.  

I merged most of your changes by hand (unzipped, then kdiff3).  I like that you fixed some of the hard-coded gunk.  I kept my manageent/commands/seed.py - you might want to grab that copy (or not).  Good job on adding the links from admin to observer/control - one less headache on game-day!

Also note I moved the Arduino code (sketchboook/**) to a first class project, so you can delete it all from your repo.  If you ever get interested in that, it's at https://github.com/joneser005/racetree

**Comment by joneser005** [comment]
I, too, am a git rookie.  I think pull requests are an all-or-nothing thing.  The cherry-picking is done on the pull request side, not the merge side?  Anyway, I merged most of your changes in this pull request by hand, so you can drop this pull request if whatever I'm about to do doesn't close it first.

I like your changes.  I think I took everything except for management/commands/seed.py and the pack 54-specific stuff.

I moved the Arduino projects into their own Git project, so you can delete those (sketchbook/**).  If you ever get interested in that, it's at https://github.com/joneser005/racetree 

Once I get fully caught up (maybe I am), I'll start working on integrating other timers (The Champ for now) in a cleaner fashion.  The code I checked it sort of munges it together - I was just adding that info as I researched, hoping to test it on the floor during our district event, but that didn't work out.  I will be getting access to their timer soon, so hopefully will have that cleaned up soon.

**Comment by joneser005** [comment]
btw, my first comment above was presumed lost - it didn't show up right away, thought I effed it up.  Anyway, the two versions of the same comment!

**Pull request closed without merging**
